on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'This deploys to production'
    steps:
    - uses: actions/checkout@v3

    - name: Azure login
      uses: Azure/login@vi
      creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Deploy ADF Azure resource manager(ARM) Template
      uses: Azure/data-factory-deploy-action@v1.2.0
      with:
        resourceGroupName: # prod-adf
        dataFactoryName: prod-adf-test
        armTemplateFile: ARMTemplateForFactory.json
        armTemplateParametersFile: ARMTemplateParametersForFactory.json
